# Generated by Django 3.1 on 2020-09-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200928_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
