# Generated by Django 3.1 on 2020-09-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
