# Generated by Django 3.1.2 on 2020-10-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
