# Generated by Django 3.1.2 on 2020-10-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201015_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.buy', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article', unique=True),
        ),
    ]
