# Generated by Django 3.1.2 on 2020-10-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201015_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article'),
        ),
    ]
