# Generated by Django 3.1.2 on 2020-10-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201015_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='buy',
            name='article_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_buy', to='app.article', unique=True, verbose_name='Category'),
        ),
    ]
