# Generated by Django 3.1.2 on 2020-10-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20201015_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='article_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sell', to='app.buy', unique=True),
        ),
    ]
