# Generated by Django 3.1.2 on 2020-10-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201015_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='article_name',
            new_name='sell_article',
        ),
    ]
